### ISSUE TITLE
Define standard post filename and xref pattern for v2

### ISSUE THREAD

**Issue by graphitefriction** [opendevise/opendevise.com#5]
We need to determine the initial template for linking between blog posts in v2 of the website.

Hand-in-hand with this is: what's our blog post file naming structure? Right now we're using `year-month-title-of-post.adoc`.

- Should we include the day?
- Should the filename be **exactly** the same as the post title?
- Or should the filename remove some prepositions/articles (e.g. a, about, the)? 
  - Conjunctions (e.g. and, or)?
  - Adjectives/adverbs (e.g. all, very)?

Here's an example of the doc attribute and xref macro we discussed on 10/25:

```
:blog-root: .../source/blog

xref:{blog-root}/post-filename-without-date[]
```
(Quick question: Why isn't the date part of the filename needed?)

This template needs to be set up before the second blog post goes live so that we can keep the series linked in chronological order.

**Comment by mojavelinux** [comment]
Although not a perfect solution, it's related to https://github.com/middleman/middleman-asciidoc/issues/38.

It would require referencing the slug of the post (which is the stem of the output filename). For example:

```
See the <<first-post.adoc#,first post>>.
```

Notice that the date prefix has been dropped.

> Should the filename be exactly the same as the post title?

This is a good question. Perhaps we can switch to year folders. That's enough to keep posts from clashing but not so annoying to navigate. I find the date in the filename to be kind of annoying anyway.

```
source/
  blog/
    2017/
      first-post.adoc
      second-post.adoc
    2018/
      new-year-new-attitude
```

The output would then mirror this structure (e.g., 2018/new-year-new-attitude).

To link from the last post to the first, you'd use:

```
See the <<../2017/first-post.adoc#,first post>>.
```

**Comment by graphitefriction** [comment]
At first glance, I was fine with sorting the blog posts into a-folder-per-year. But then ...

There is a potential gray area - popular articles that we update / add info to over the years - they'll stay in the year they originally were published (which will be seen in the URL) but this calls for displaying a revised/updated date line as well as the originally published date line.

Which makes me question organizing by year - how does the year help me, as the author, find an article? I can't remember the year I graduated college. Am I going to remember the year I wrote something?

What about sorting them into folders by author? But what happens when an article is written by multiple authors?
Which then just leads me into, why not sort articles into Antora-style modules? But does that mean 99% of our stuff will want to go into a folder called documentation :woman_facepalming: 

Of course, all this stems from the fact that I HATE that URLs mirror the filesystem. :rage:

Other topics:

Definitely :+1: for dropping the date from the filename.

As for naming the file - for now, let's map filename and doctitle 1-to-1, and just deviate if a doctitle is extra-long (which should really trigger: Why the :duck: is my doctitle so long???) or weird-ish.

:+1: cross referencing slug, already added and working.

**Comment by mojavelinux** [comment]
> Definitely :+1: for dropping the date from the filename.

I've made the switch to an arbitrary 4-digit ID at the beginning of the filename instead of the date. The date is now controlled in the AsciiDoc header. The only purpose of the ID is to help with sorting. In fact, there's not stopping you from using the same ID twice. The numbers don't have to be the order of publishing since they don't get propagated. Instead, just take the next number when adding a new article. 

Example:

```
0001-hello.adoc
0002-content-is-sovereign.adoc
0003-standard-project-structure-for-docs.adoc
```

**Comment by mojavelinux** [comment]
> As for naming the file - for now, let's map filename and doctitle 1-to-1, and just deviate if a doctitle is extra-long (which should really trigger: Why the :duck: is my doctitle so long???) or weird-ish.

For now, we're going to take the textual portion of the filename and make that the name of the output file. There's no requirement that this match the doctitle exactly. In fact, there's benefits for it being shorter. It just shouldn't diverge from the document title. This may mean renaming the file a few times during editing as the doctitle is updated. It's what you would call the slug. Derived from the doctitle, but not necessarily matching it 1-to-1.

**Comment by mojavelinux** [comment]
Btw, you can never use the same slug twice...at least, for now.

**Comment by mojavelinux** [comment]
The way you link to another post is you refer to it's slug followed by ".adoc". In other words:

```
<<content-is-sovereign.adoc#,Content is Sovereign>>
```

You do not include the arbitrary ID in the xref.

There is one addition think you need to make a reference from an article to another article. You must add the following line below the AsciiDoc header (not inside of it).

```
ifdef::relfilesuffix[:outfilesuffix: {relfilesuffix}]
```

This is necessary until Asciidoctor 1.5.7 is released with support for relfilesuffix. The hack we use in other site generators doesn't work with Middleman, so we had to make a change to Asciidoctor.

**Comment by mojavelinux** [comment]
I'm going to document this in the README.

**Comment by mojavelinux** [comment]
Documented. See https://gitlab.com/opendevise/opendevise.com

**Comment by mojavelinux** [comment]
We should probably establish some rules for how the slug is created from the doctitle.
